### ISSUE TITLE
Explosion ObjectType?

### ISSUE THREAD

**Issue by raptor** [bitfighter/bitfighter#403]
_From [corteocarl](https://code.google.com/u/corteocarl/) on February 17, 2014 19:11:34_

What new feature or enhancement would you like to request? Just thought of this, it would be neat to have an Explosion Object instead of just setting the Bursts' velocity to 0 :)

_Original issue: http://code.google.com/p/bitfighter/issues/detail?id=403_

**Comment by raptor** [comment]
_From [amginea4...@gmail.com](https://code.google.com/u/118060042413138816983/) on March 08, 2014 16:51:39_

Clarify isnt there already mines implemented?

**Comment by raptor** [comment]
_From [watusim...@bitfighter.org](https://code.google.com/u/105427273526970468779/) on March 12, 2014 12:30:38_

I don't understand what this is about.  Is this a request for a way for levelgens to create an explosion effect?

**Comment by raptor** [comment]
_From [corteocarl](https://code.google.com/u/corteocarl/) on September 06, 2014 17:01:51_

Oh wow sorry, I was think of some kind of object that could be set to do x amount of damage, I am guessing it would explode instantly when it gets added to the game, and then gets destroyed.

**Comment by raptor** [comment]
Closing old issue. Won't likely be implemented or can already be done in some other way (e.g. levelgen)

**Comment by eykamp** [comment]
My interpretation of this issue is that they want a way for a levelgen to trigger an explosion effect.  This can be simulated by inserting a burst, but the request is for a more elegant mechanism for doing it.  (This would probably require a new major-version release, but perhaps there could be a new protocol for visual effects; insert an explosion effect, sparks, text like our "Goal", etc.)
