### ISSUE TITLE
Make sure levelgen errors thrown by LuaScriptRunner::runFunction() are caught

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#534]
Right now they seem to bring the whole game down.  Sample lua code that reproduces the crash when run in a levelgen:

    gameInfo = bf:getGameInfo()
    team = gameInfo:getTeam(0)  -- 0 is an invalid index, and causes mayhem!

**Comment by raptor** [comment]
What..  really??  Is this because of LuaJIT?

**Comment by eykamp** [comment]
I don't know, but I suspect not... I think it is related to exception handling within the C++ code.  But I haven't really investigated.

**Comment by eykamp** [comment]
This block crashes where noted.  I added the try/catch handler around the block, and I really don't see why the catch doesn't handle the throw.

    try{
        if(error)
        {
           string msg = lua_tostring(L, -1);
           lua_pop(L, 1);    // Remove the message from the stack, so it won't appear in our stack dump

           string text = "In method " + string(function) +"():\n" + msg;

           throw LuaException(text);
           // Unhandled exception at 0x00004020 in bitfighter_debug.exe: 0xC0000005: Access violation (parameters: 0x00000008).
        }
     }catch(...)
     {
        logprintf("Error!");
     }

**Comment by raptor** [comment]
I'm  not sure if this is relevant, but LuaJIT does not integrate with c++ exceptions because of various low-level (really low-level) issues:

http://luajit.org/extensions.html#exceptions

See commit 3f5b49fc2bc8e0ffcc34003c263c8a9998d99b1e where I had to handle exceptions in a slightly different manner since converting to LuaJIT

**Comment by raptor** [comment]
Actually, this is probably exactly the issue:  just use the `THROW_LUA_EXCEPTION()` macro instead of `throw LuaException()`

**Comment by eykamp** [comment]
I don't think that's it.  The macro does, sort of, fix the problem, but instead throws Bitfighter into an endless loop ending in when memory is exhausted.

My reading of that line is that C++ is throwing an error, and, for some reason, not catching it shortly thereafter.  I don't really see how Lua would be involved at this stage,.

**Comment by eykamp** [comment]
After reading the link, it may be more relevant than I thought. I need to see if the behavior is different on win32 and win64, which might confirm that the info on the link is relevant.

**Comment by raptor** [comment]
Since you got stack overflow-like behavior, I suspect that this exception is thrown from originating code in Lua.  This is what is meant by "not safe to throw C++ exceptions across Lua frames" on the LuaJIT website.

If this is the case, then we can't throw an exception here and we have already thrown a `THROW_LUA_EXCEPTION`.  A different way to handle this error must be written - perhaps with just a `logprintf`?

**Comment by eykamp** [comment]
That probably won't cut it. The exception handler must also terminate the script and carry out an orderly exit, while still leaving the rest of the Lua environment intact. 

I'll need to investigate how the current exception handler handles things and see if there is a way to duplicate that which will work with Lua jit.

**Comment by eykamp** [comment]
Fixed.  Also eliminated a few other try/catches that weren't really necessary, tested most others to verify they didn't cause mayhem.
