### ISSUE TITLE
Up/down arrow in chat should recall previous messages

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#542]
That is, if it doesn't already work this way :-)

**Comment by raptor** [comment]
We already have the CTRL+M mechanism to switch between chat modes. There is a limited history of, I think, 24 messages. 

I suppose the whole message rendering could be rewritten to have a single message renderer instead of 3 for all the modes and add this feature. It would act more like a scrollable message window instead.

Closing for now.

**Comment by eykamp** [comment]
Actually this is a different thing.  Rather than explain it, I'll just do it!

**Comment by eykamp** [comment]
Done!

**Comment by raptor** [comment]
Command history!  Great idea!

**Comment by eykamp** [comment]
Well, that would be another name for it :-)

Two additional thoughts: 1) save commands only (currently all chat messages are stored); and 2) persist history between sessions?  (either all messages or commands only)
