### ISSUE TITLE
Figure out why point is null

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#544]
Figure out why this is so, and either document it or fix it

https://github.com/bitfighter/bitfighter/commit/70b7fe91e48b374e0a97a3fffe1db1f2c14ad696#commitcomment-13165113

Ideally, we'd convert the if() to an assert.

**Comment by raptor** [comment]
Confirmed crashing in editor when commenting out the if() part.  Diagnosing...

**Comment by raptor** [comment]
Ah ha.  It happens when multiple objects pass in a collision polygon pointer like in `EngineeredItem::calcExtents()`.  Many times this may be NULL because it isn't a real game object, I think, like in the dock.  

There is also another Rect constructor that is crash-prone: `Rect(const Rect *r)`.  We just haven't used it in a crashy way yet.

I'm not sure what a proper fix might be; maybe use references with object polygons? or maybe just leave it alone.

**Comment by eykamp** [comment]
A reference is probably the best way, if it can be done.

**Comment by eykamp** [comment]
I think I fixed this tonight.  I didn't realize we had a issue for it.
