### ISSUE TITLE
Installer: Game doesn't close when being updated

### ISSUE THREAD

**Issue by eykamp** [bitfighter/bitfighter#599]
In upgrading using the Win32 installer after being prompted that a new version is available, the installer should close the running copy of the game to let the install proceed.  It used to do this, but hasn't for the last several releases.  It should.

**Comment by raptor** [comment]
This is finally resolved.  The issue was that WinGup looks for the classname of the window, not the window name, to shutdown the calling process.  The class name happens to always be  `SDL_app` because it is hard-coded into SDL2.  Fixed in 788b21fde7dbf3ec5aba6e2ef3427f08ebe4bbce

This may close other running SDL2 apps as well, as WinGup uses a shotgun approach.
