### ISSUE TITLE
Rotating the resource and line items in this level places them at infinity

### ISSUE THREAD

**Issue by bobdaduck** [bitfighter/bitfighter#636]
1) select resources and line item
2) press R or shift+R or any of the other rotation functions
_Items disappear_
3) press Z to focus on selection
_cursor:getPos() returns NaN_

[rotationError.zip](https://github.com/bitfighter/bitfighter/files/5180289/rotationError.zip)

**Comment by raptor** [comment]
That's awesome!

**Comment by raptor** [comment]
Cause of the bug is when multiple objects are selected (more than 2), the center-finding algorithm assumes that there will be some polygon created from all the points and that the area of it is not zero. Since all these objects are on a line, the area is zero and breaks the algorithm.  A LineItem with 3 points all in a line will also trigger it.

**Comment by raptor** [comment]
Fix with revisions 9c50ca6bde211bbdf714d6ceb38153cfaf50aab0 and 64841cbfc3d16099def67c4f47c3382bc5c7ad38
