### ISSUE TITLE
Level editor TextItem modifications

### ISSUE THREAD

**Issue by Jomskylark** [bitfighter/bitfighter#654]
Hi, I'm not sure if this is the best place to put this, but Discord chat seemed kinda messy. I am wondering if there could be some small modifications for the TextItem in the level editor:

1. **Hold shift + arrow key to move the text cursor word by word**
2. **Predetermined text sizes, controllable from attributes menu**
3. **Global text setting**

*Note: I made a simple mockup screenshot for how these might look:*

![Mock-up](https://i.imgur.com/h2LYjmm.png)

**1. Hold shift + arrow key to move the text cursor word by word:** Currently, a line of text is edited by holding an arrow key to move the flashing cursor from letter to letter. If the text is long, this can take several seconds to reach a specific part of the text. My suggestion is holding shift plus the arrow key would move the text cursor word by word (or more aptly, from one space to the next space) to expedite the editing process.

**2. Predetermined text sizes, controllable from attributes menu:** Currently, text size is determined by how far one point of a TextItem is from its other point. If a TextItem has more or fewer characters than another TextItem, its size will adjust to fit the space available between the two points. Adjusting multiple TextItems of varying lengths to match sizes can be cumbersome and time-consuming, as it requires precise adjustments of each individual TextItem.

My suggestion is predetermined text sizes that would determine a TextItem's size, regardless of how many characters were in the TextItem. These sizes could be controlled from the attributes menu, much like what exists for Asteroids. A TextItem's endpoints would no longer change its size, but could still be drug around to change the angle. However, if a TextItem did not have a size listed in the .level file, it would default to the amount of room between each endpoint (ie. the current system) in order to preserve existing levels.

Range of sizes: Ideally there would be a range of at least 20 sizes to give levelmakers flexibility. The height of each text size would depend on what would be easiest to program, but perhaps the smallest size could have a height (for lowercase letters) of one fourth of one small square in the level editor grid. The largest size could then have a height of ten small squares for lowercase letters. In this example, sizes would range from 1 to 40. But this is just one possibility.

**3. Global text setting:** Currently, text in the color of a team can only be viewed by that team's members. LineItems have a global setting to be viewed by all teams, which is very helpful for developing a level's aesthetic appearance. My suggestion is to provide TextItems with this setting as well. There are many creative applications for Global text; one of the simplest is to call attention to certain words by making one TextItem one color while the other TextItems remain a different color.

Thank you for your consideration!

-Bill

**Comment by eykamp** [comment]
1. Certainly doable; I'd prefer the modifier be Ctrl rather than Shift, as Shift is typically used for extending a selection.
2.  Also seems doable, though I'd suggest a text box for entry of a size rather than a pick-list. Using editor grid squares as a sizing metric seems like a good idea.  Entering 0 or -1 (or nothing) would revert the behavior to what it is currently.
3.  Also seems doable and reasonable.

A couple of meta-comments; first, this is a great place to make suggestions like this, especially for things that aren't likely to require a lot of community discussion to hash out.  Second, I think you did a great job writing up the request in a clear and understandable fashion (not all requests are so well articulated).  These could be implemented by a new dev without much further explanation of what the goal was.  Third, it would be better to make this three items instead of one, so they can be worked on and discussed independently.

In that light, could you close this issue and create three new ones using the explanations provided for each?  I'll append my comments above as needed.

**Comment by Jomskylark** [comment]
Hey, thanks for the kind and helpful comments. Those suggestions seem reasonable, whatever works best is great. I will edit this current thread to only be for the first item (expedited text cursor) and make new issues for the other two items.

Thanks!

**Comment by Jomskylark** [comment]
Whoops, thought I did this already...
