### ISSUE TITLE
Discussion: Pre-merge checks?

### ISSUE THREAD

**Issue by elementc** [bitfighter/bitfighter#669]
Hi, wanted to kick off a discussion following the stuff about getting bitfighter on flathub to take the maintainers' temperature on adding some automation to this project's github, for getting extra checks on whether a particular change breaks the build.

I worked with @greenfire27 last year to get github actions set up for Torque2D which get kicked off on changes to particular branches or when new PRs come in. These build and package up the engine for Windows, Mac, and Linux on supported platforms, here's master run for them:
https://github.com/TorqueGameEngines/Torque2D/actions/runs/2571125661
and here's a PR run for them:
https://github.com/TorqueGameEngines/Torque2D/pull/43/checks

Would this be interesting for y'all? I have some bandwidth this hacktoberfest to set these up if it's helpful for y'all.

**Comment by fordcars** [comment]
Hi @elementc, I'm always down for more automation and DevOps. I think the reason we don't have much of a pipeline right now is due to the fact that the dev team is very small; PRs are actually quite rare. We would probably need to evaluate the benefits vs. cost as of right now, but I'm open to it. Wonder what the other devs think?

**Comment by eykamp** [comment]
Temperamentally, I'm supportive.  I've always seen BF as a way to do new stuff (which, occasionally turns out to be useful, like adding a Lua interpreter).  That said, given the low level of activity of the project, whatever we do has to be self-sustaining, that is, it can't require a lot of tinkering or hand-holding.

**Comment by raptor** [comment]
Is this a suggestion to use Github Actions to build the game? Sounds good to me.

**Comment by elementc** [comment]
> Is this a suggestion to use Github Actions to build the game? Sounds good to me.

That's the suggestion! I'll take a run at it and see how reliable / flaky it is :)

**Comment by elementc** [comment]
Fairly pleased with reliability on my first stab, so going to close this discussion and proceed with PRs! Thanks for the input!
